export type ShortcutAction =
  | 'playPause'
  | 'undo'
  | 'redo'
  | 'delete'
  | 'copy'
  | 'paste'
  | 'cut'
  | 'split'
  | 'zoomIn'
  | 'zoomOut'
  | 'zoomFit'
  | 'snap'
  | 'selectTool'
  | 'razorTool'
  | 'frameBack'
  | 'frameForward'
  | 'import'
  | 'goStart'
  | 'goEnd'
  | 'save'
  | 'open'

export function matchShortcut(e: KeyboardEvent): ShortcutAction | null {
  const mod = e.metaKey || e.ctrlKey
  const key = e.key.toLowerCase()

  if (mod && key === 'z' && e.shiftKey) return 'redo'
  if (mod && key === 'z') return 'undo'
  if (mod && key === 'y') return 'redo'
  if (mod && key === 'c') return 'copy'
  if (mod && key === 'v') return 'paste'
  if (mod && key === 'x') return 'cut'
  if (mod && key === 'i') return 'import'
  if (mod && key === 's') return 'save'
  if (mod && key === 'o') return 'open'
  if (key === ' ' || key === 'k') return 'playPause'
  if (key === 'delete' || key === 'backspace') return 'delete'
  if (key === 'b') return 'split'
  if (key === 'n') return 'snap'
  if (key === 'a' && !mod) return 'selectTool'
  if (key === 'r' && !mod) return 'razorTool'
  if (key === '=' || key === '+') return 'zoomIn'
  if (key === '-') return 'zoomOut'
  if (key === '0' && mod) return 'zoomFit'
  if (key === 'arrowleft' || key === 'j') return 'frameBack'
  if (key === 'arrowright' || key === 'l') return 'frameForward'
  if (key === 'home') return 'goStart'
  if (key === 'end') return 'goEnd'
  return null
}
